--Nama : Felix Erlangga Ananta
--NIM  : 103122400038

--Soal 1
SELECT COUNT(*) 
AS "JUMLAH FILM"
FROM FILM;

--Soal 2
SELECT COUNT(DISTINCT f.JUDUL) AS "JUMLAH FILM DIPUTAR"
FROM JADWAL j
JOIN FILM f ON j.ID_FILM = f.ID_FILM;

--Soal 3 Part 1
SELECT ID_MEMBER, COUNT(*) AS "JUMLAH NONTON"
FROM TRANSAKSI
GROUP BY ID_MEMBER
HAVING COUNT(*) > 2;

--Soal 3 Part 2
SELECT ID_MEMBER, COUNT(*) AS "JUMLAH NONTON"
FROM TRANSAKSI
GROUP BY ID_MEMBER
HAVING COUNT(*) > 3;

--Soal 3 Part 3
SELECT ID_MEMBER, COUNT(*) AS "JUMLAH NONTON"
FROM TRANSAKSI
GROUP BY ID_MEMBER
HAVING COUNT(*) > 4;

--Soal 3 Part 4
SELECT ID_MEMBER, COUNT(*) AS "JUMLAH NONTON"
FROM TRANSAKSI
GROUP BY ID_MEMBER
HAVING COUNT(*) > 5;

--Soal 4
SELECT m.ID_MEMBER,
       m.NAMA,
       FLOOR(MONTHS_BETWEEN(SYSDATE, m.TGL_LAHIR)/12) AS "UMUR",
       COUNT(tr.KODE_PEMESANAN) AS "JUMLAH NONTON"
FROM MEMBER m
JOIN TRANSAKSI tr ON m.ID_MEMBER = tr.ID_MEMBER
WHERE m.TGL_LAHIR = (
    SELECT MAX(TGL_LAHIR)
    FROM MEMBER
)
GROUP BY m.ID_MEMBER, m.NAMA, m.TGL_LAHIR;

--Soal 5
SELECT TO_CHAR(TGL_LAHIR, 'MONTH') AS "BULAN",
       COUNT(*) AS "JUMLAH MEMBER"
FROM MEMBER
GROUP BY TO_CHAR(TGL_LAHIR, 'MONTH')
ORDER BY "BULAN";

--Soal 6
SELECT f.JUDUL AS "JUDUL FILM",
       COUNT(j.ID_JADWAL) AS "JUMLAH JADWAL"
FROM FILM f
JOIN JADWAL j ON f.ID_FILM = j.ID_FILM
GROUP BY f.JUDUL;