--nama: Felix Erlangga Ananta
--nim: 103122400038
--Soal 1
SELECT 
    th.ID_THEATER AS NOMOR_TEATER,
    f.JUDUL AS JUDUL_FILM,
    SUM(th.HARGA) AS TOTAL_PENDAPATAN
FROM TRANSAKSI t
JOIN JADWAL j ON t.ID_JADWAL = j.ID_JADWAL
JOIN FILM f ON j.ID_FILM = f.ID_FILM
JOIN THEATER th ON j.ID_THEATER = th.ID_THEATER
GROUP BY th.ID_THEATER, f.JUDUL
HAVING SUM(th.HARGA) > 150000;
--Soal 2
SELECT f.JUDUL, COUNT(t.KODE_PEMESANAN) AS total_penonton
FROM FILM f
JOIN JADWAL j ON f.ID_FILM = j.ID_FILM
JOIN TRANSAKSI t ON j.ID_JADWAL = t.ID_JADWAL
WHERE t.STATUS = 'pesan'
GROUP BY f.JUDUL
ORDER BY total_penonton DESC
FETCH FIRST 1 ROW ONLY;
--Soal 3
SELECT th.ID_THEATER, AVG(th.HARGA) AS rata_rata_pendapatan
FROM THEATER th
JOIN JADWAL j ON th.ID_THEATER = j.ID_THEATER
JOIN TRANSAKSI t ON j.ID_JADWAL = t.ID_JADWAL
GROUP BY th.ID_THEATER;
--Soal 4
SELECT f.JUDUL, j.ID_THEATER, COUNT(j.ID_JADWAL) AS jumlah_diputar
FROM FILM f
JOIN JADWAL j ON f.ID_FILM = j.ID_FILM
WHERE f.JUDUL = 'Habibie Ainun 3'
GROUP BY f.JUDUL, j.ID_THEATER;