-- Nama : Felix Erlangga Ananta
-- NIM : 103122400038

--Soal 1
SELECT f.JUDUL AS "JUDUL",
       j.ID_THEATER AS "ID_THEATER",
       TO_CHAR(j.PERIODE_START, 'DD-MM-YYYY') AS "PERIODE_START",
       EXTRACT(DAY FROM NUMTODSINTERVAL(j.PERIODE_END - j.PERIODE_START, 'DAY')) 
       || ' hari' AS "LAMA WAKTU"
FROM FILM f
JOIN JADWAL j ON f.ID_FILM = j.ID_FILM
WHERE f.JUDUL = 'Habibie Ainun 3';

--Soal 2
SELECT t.ID_THEATER AS "ID THEATER",
       f.JUDUL AS "JUDUL",
       t.KELAS AS "KELAS",
       t.HARGA AS "HARGA",
       CASE 
           WHEN t.HARGA < 50000 THEN 'Murah'
           WHEN t.HARGA > 75000 THEN 'Mahal'
           ELSE 'Normal'
       END AS "KATEGORI"
FROM THEATER t
JOIN JADWAL j ON t.ID_THEATER = j.ID_THEATER
JOIN FILM f ON j.ID_FILM = f.ID_FILM;

--Soal 3
SELECT m.ID_MEMBER AS "ID MEMBER",
       t.HARGA AS "HARGA",
       FLOOR(MONTHS_BETWEEN(SYSDATE, m.TGL_LAHIR)/12) AS "UMUR",
       CASE 
           WHEN FLOOR(MONTHS_BETWEEN(SYSDATE, m.TGL_LAHIR)/12) <= 32 
           THEN t.HARGA * 0.9
           ELSE t.HARGA
       END AS "SALE"
FROM MEMBER m
JOIN TRANSAKSI tr ON m.ID_MEMBER = tr.ID_MEMBER
JOIN JADWAL j ON tr.ID_JADWAL = j.ID_JADWAL
JOIN THEATER t ON j.ID_THEATER = t.ID_THEATER
ORDER BY "UMUR";

--Soal 4
SELECT m.ID_MEMBER AS "ID_MEMBER",
       m.NAMA AS "NAMA_MEMBER",
       f.JUDUL AS "JUDUL"
FROM MEMBER m
JOIN TRANSAKSI tr ON m.ID_MEMBER = tr.ID_MEMBER
JOIN JADWAL j ON tr.ID_JADWAL = j.ID_JADWAL
JOIN FILM f ON j.ID_FILM = f.ID_FILM
WHERE f.DURASI >= 100
AND TO_NUMBER(SUBSTR(m.NO_HP, -1)) = 8;

--Soal 5
SELECT m.ID_MEMBER AS "ID_MEMBER",
       f.ID_FILM AS "ID_FILM",
       j.ID_THEATER AS "ID_THEATER",
       t.HARGA AS "HARGA",
       CASE 
           WHEN f.JUDUL = 'Keluarga Cemara'
                AND tr.TANGGAL >= TO_DATE('2019-12-19', 'YYYY-MM-DD')
           THEN t.HARGA * 0.3
           ELSE t.HARGA
       END AS "SALE"
FROM TRANSAKSI tr
JOIN MEMBER m ON tr.ID_MEMBER = m.ID_MEMBER
JOIN JADWAL j ON tr.ID_JADWAL = j.ID_JADWAL
JOIN FILM f ON j.ID_FILM = f.ID_FILM
JOIN THEATER t ON j.ID_THEATER = t.ID_THEATER;